### ISSUE TITLE
BadRequest : The certificate with thumbprint .... was not found.

### ISSUE THREAD

**Issue by AlexeyKamenew** [MSOpenTech/vagrant-azure#76]
Vagrant 1.7.2
vagrant-azure (1.1.1)
-- mode: ruby --
vi: set ft=ruby :

Vagrant.configure(2) do |config|
config.vm.box = "azure"
config.vm.provider :azure do |azure|
azure.vm_size = 'ExtraSmall'
azure.mgmt_certificate = '...'
azure.mgmt_endpoint = 'https://management.core.windows.net'
azure.subscription_id = '...'
azure.vm_image = '2b171e93f07c4903bcad35bda10acf22__CoreOS-Stable-522.6.0'                                                                
azure.storage_acct_name = 'EXISTING STORAGE ACCOUNT NAME'
azure.vm_user = '...'                                                                                                                
azure.vm_password = '...'                                                                                                         
azure.vm_name = 'coreos-node-1'                                                                                                           
azure.cloud_service_name = '...'                                                                                                 
azure.deployment_name = 'coreos-node-1'                                                                                                   
azure.vm_location = 'West Europe'                                                                                                         
azure.ssh_private_key_file = '...'                                                                           
azure.ssh_certificate_file = '...'                                                                           
azure.ssh_port = '...'                                                                                                                   
azure.tcp_endpoints = '80'                                                                                                                
end
config.ssh.username = '...'
config.ssh.password = '...'
end

vagrant up --provider=azure

BadRequest : The certificate with thumbprint .... was not found.
/home/kamenew/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/core/utility.rb:93:in `error_with_exit': BadRequest : The certificate with thumbprint .... was not found. (RuntimeError)
	from /home/kamenew/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_management/management_http_request.rb:81:in `wait_for_completion'
	from /home/kamenew/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_management/management_http_request.rb:55:in `call'
	from /home/kamenew/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:202:in `add_role'
	from /home/kamenew/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/vagrant_azure_service.rb:38:in `method_missing'
	from /home/kamenew/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/run_instance.rb:99:in `block in call'
	from /home/kamenew/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/run_instance.rb:74:in `synchronize'
	from /home/kamenew/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/run_instance.rb:74:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/kamenew/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/os_type.rb:29:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/kamenew/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/connect_azure.rb:44:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	from /opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	from /opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
kamenew@gux:~/Projects/TheProject/env/azure$

**Comment by AlexeyKamenew** [comment]
Certificates were made with instructions 
https://github.com/MSOpenTech/Vagrant-Azure
Using openssl (Linux/Mac)

**Comment by devigned** [comment]
If you cat your management .pem, does it have both a public and private key in it?

**Comment by devigned** [comment]
ping?

**Comment by devigned** [comment]
added in some documentation on how the certs are handled. The latest bits are in master. Give it a shot and ping back if you are still having issues.

**Comment by kfm82** [comment]
Hello there. We are having the exact same problem using Vagrant version 1.7.4 and vagrant-azure plugin version 1.1.1. We have tried generating multiple certificates (1024 and 2048 bit length) and running vagrant up --provider=azure from various MacBooks running both Mavericks and Yosemite. Since this is for a mission critical project, any speedy feedback would be highly appreciated.

**Comment by falkorichter** [comment]
The same problems occurs on my machine (OSX 10.9.5) with my own certificate. The thumbprint mentioned in the error message 100% matches the one we uploaded

```
Deployment exists, adding role...
Deployment in progress...
BadRequest : The certificate with thumbprint 04C3A30A6A93D535F20BE8C269D4C3DEFD5FDD6D was not found.
/Users/falkorichter/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/core/utility.rb:93:in `error_with_exit': BadRequest : The certificate with thumbprint 04C3A30A6A93D535F20BE8C269D4C3DEFD5FDD6D was not found. (RuntimeError)
	from /Users/falkorichter/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_management/management_http_request.rb:81:in `wait_for_completion'
	from /Users/falkorichter/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_management/management_http_request.rb:55:in `call'
	from /Users/falkorichter/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:202:in `add_role'
	from /Users/falkorichter/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/vagrant_azure_service.rb:38:in `method_missing'
	from /Users/falkorichter/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/run_instance.rb:99:in `block in call'
	from /Users/falkorichter/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/run_instance.rb:74:in `synchronize'
	from /Users/falkorichter/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/run_instance.rb:74:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/falkorichter/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/os_type.rb:29:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/falkorichter/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/connect_azure.rb:44:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	from /opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	from /opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

<img width="874" alt="screen shot 2015-08-10 at 14 49 29" src="https://cloud.githubusercontent.com/assets/50506/9171840/13d19d1a-3f6f-11e5-8088-c99f3a889517.png">

**Comment by devigned** [comment]
I believe this is fixed in vagrant-azure 1.2.0

**Comment by kfm82** [comment]
After updating to vagrant-azure 1.2.1, we no longer get the Thumbprint Mismatch error, so that's a definite improvement. We are, however, still seeing this (previously unnoticed) alert:

Failed to create virtual machine : ConflictError : The specified deployment slot Production is occupied.

However, this may be on account of our current VM cluster layout / run state, so we will only report back here if we are unable to resolve it on our own. Thank you so far!

**Comment by devigned** [comment]
Great news! 

It should target the production slot by default. Perhaps, target a different cloud service for your vagrant use.

**Comment by lionelperrin** [comment]
Hello,

I have the feeling that this issue still exists with the current release 1.2.1.
I noticed that 'add_role' is no longer called in this version because the test in action/run_instance.rb to check if `add_role` or `create_virtual_machine` should be done is not working anymore.

The call `ManagementHttpRequest.new` at line 76 should be replaced by `Azure::BaseManagement::ManagementHttpRequest.new`. Doing so makes possible to call add_role when creating a second vm instance under an existing cloud service.

Unfortunately, the call to add_role leads to: `BadRequest : The certificate with thumbprint xxx was not found`. Note that other calls like create_virtual_machine are working fine.

**Comment by kfm82** [comment]
@lionelperrin Thanks a lot for weighing in here. @devigned Is there any likelihood of @lionelperrin's proposed changes being applied to master/upstream anytime soon?
